### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by Alessandro994**
Hi, I really like your project and your goal (also because I've been questionated by police while I was Geocaching too!)
Thus I offer you an italian translation of the short text. I've only added one file in /res.
Best regards and happy caching!
Alessandro

### CODE REVIEW

**Comment by fereira** [comment]
Merged in Italian version

**Comment by fereira** [comment]
Thanks for the addition.   Are you in Rome?   I was questioned by police there after finding the cache near the Arc de Constantine.

**Comment by Alessandro994** [comment]
No, I live in Northern Italy, near Verona. 
The unconfortable meeting with policemen happened while I was geocaching in Wien, Austria. Luckily there was also a german man with his wife and after we explained them we were not placing any bomb but playing this strange game called Geocaching they let us go.

**Comment by fereira** [comment]
I’ve been to Milan a couple of times but that’s about as close to Verona as I’ve been.  I’ve also been to Rome six times.   I do a fair amount of work with the Food and Agriculture Organization of the UN at their headquarters in Rome and have several Italian friends there.

**Pull request merged**
